### ISSUE TITLE
no null check on ConnectionAccess.getChannel() causes crash with Create

### ISSUE THREAD

**Issue by TropheusJ** [KyoriPowered/adventure-platform-fabric#14]
when used with Create, placing a deployer crashes the game due to the fake networking resulting in a null channel.
https://github.com/Fabricators-of-Create/Create/issues/117

**Comment by zml2008** [comment]
If you look at everywhere Connections are created in vanilla (the static factory methods in `Connection`, and `net.minecraft.server.network.ServerConnectionListener.startTcpServerListener()`, you'll see that every returned `Connection` object is initialized with a channel by the time the method returns. This is also supported by the fact that `channel` is an un-annotated field in a package Mojang has annotated with `FieldsAreNonnullByDefault`. 

However, this issue has come up before -- see the discussion at https://github.com/gnembon/fabric-carpet/issues/1142. I expect as long as people continue rolling their own fake player systems, we'll see similar issues. Because of that, I think the most appropriate long-term solution to this issue is to get a fake player system added to Fabric API. I'll write up an issue there.

**Comment by itsdinkd** [comment]
@zml2008 Any luck on that issue you wrote up to FAPI?

**Comment by iczero** [comment]
Haven't tested this much but I hacked a stupid fix that may or may not fix stuff.

- Cherry-pick this commit: https://github.com/iczero/adventure-platform-fabric/commit/7bce0fe896c1f7e8900888a901d764f2ae61a760
- Rebuild `adventure-platform-fabric` (`./gradlew build`)
- Copy `build/libs/adventure-platform-fabric-<version>.jar` into mods folder
- Unzip conflicting mods, remove bad version of `adventure-platform-fabric` from `META-INF/jars`

**Comment by zml2008** [comment]
Please don't enable bad mod development practices.

**Comment by iczero** [comment]
I am not a mod developer, only a mod player. I simply wish to use mods without conflicts. I do not in any way expect for this to be upstream. It's been pretty much an entire year and there still doesn't exist a standard fake players API.
